# app.py
import streamlit as st
import pickle
import pandas as pd

@st.cache_resource
def load_model():
    with open("model.pkl", "rb") as f:
        model, vectorizer = pickle.load(f)
    return model, vectorizer

model, vectorizer = load_model()

def predict_message(msg):
    vec = vectorizer.transform([msg])
    pred = model.predict(vec)[0]
    prob = None
    if hasattr(model, "predict_proba"):
        prob = model.predict_proba(vec)[0].max()
    label = "Spam" if pred == 1 else "Ham"
    return label, prob

st.set_page_config(page_title="Spam vs Ham Detector", page_icon="📨", layout="centered")
st.title("📨 Spam vs Ham Detector")
st.markdown("Type a message (SMS) below or upload a file (CSV) and this model will predict whether it's Spam or Ham.")

# --- Single message prediction ---
st.subheader("Single message prediction")

# Initialize session state for the text area
if "user_input" not in st.session_state:
    st.session_state.user_input = ""

# Text area linked to session state
st.session_state.user_input = st.text_area(
    "Enter message to predict",
    value=st.session_state.user_input,
    height=120
)

col1, col2 = st.columns([1, 1])

with col1:
    if st.button("Predict"):
        if not st.session_state.user_input.strip():
            st.warning("Please enter a message to predict.")
        else:
            label, prob = predict_message(st.session_state.user_input)
            if label == "Spam":
                st.error(f"Prediction: {label}")
            else:
                st.success(f"Prediction: {label}")
            if prob is not None:
                st.write(f"Confidence: {prob:.2%}")

with col2:
    if st.button("Clear"):
        st.session_state.user_input = ""  # Clear the text
        st.rerun()           # Refresh UI

# Quick example buttons
st.subheader("Quick examples")

# Example data
spam_examples = {
    "Free iPhone (spam)": "Congratulations! You've won a free iPhone. Click here to claim.",
    "Earn money (spam)": "Earn $5000/week working from home. Limited time offer!",
    "Loan granted (spam)": "Your loan has been approved! Click to proceed.",
    "Holiday prize (spam)": "You've won a holiday trip! Claim now."
}

ham_examples = {
    "Meeting (ham)": "Hey, are we still meeting at 5 pm for the project discussion?",
    "Birthday (ham)": "Happy Birthday! Hope you have a wonderful day.",
    "Delivery plan (ham)": "Your delivery is scheduled for tomorrow.",
    "Gym (ham)": "Reminder: Your gym session is at 6 pm."
}

# First row - Spam
cols = st.columns(len(spam_examples))
for i, (label, text) in enumerate(spam_examples.items()):
    if cols[i].button(label, key=f"spam_btn_{i}"):
        st.session_state.user_message = text

# Second row - Ham
cols = st.columns(len(ham_examples))
for i, (label, text) in enumerate(ham_examples.items()):
    if cols[i].button(label, key=f"ham_btn_{i}"):
        st.session_state.user_message = text


if 'example' in st.session_state:
    st.text_area("Example (editable)", value=st.session_state['example'], key="example_box")

# Batch prediction via CSV
st.subheader("Batch prediction (CSV)")
st.markdown("Upload a CSV with a column named message. The app will output predictions for each row.")
uploaded_file = st.file_uploader("Upload CSV", type=["csv"])
if uploaded_file is not None:
    try:
        df = pd.read_csv(uploaded_file)
        if "message" not in df.columns:
            st.error("CSV must contain a column named message.")
        else:
            st.write("First 5 rows of your file:")
            st.dataframe(df.head())
            if st.button("Run batch prediction"):
                df['prediction'] = df['message'].apply(lambda t: predict_message(str(t))[0])
                st.success("Predictions complete.")
                st.dataframe(df.head(20))
                # Provide download
                csv = df.to_csv(index=False).encode('utf-8')
                st.download_button("Download predictions CSV", data=csv, file_name="predictions.csv", mime="text/csv")
    except Exception as e:
        st.error(f"Error reading CSV: {e}")

#footer/notes
st.markdown("---")
st.markdown(
    """
    📝 Notes & Tips- """)
st.markdown(
    """
    *Disclaimer:* The predictions provided are generated by a machine learning model and are intended for demonstration and educational purposes only.  
    *No Guarantee:* While efforts have been made to ensure accuracy, results may not be 100% reliable in real-world scenarios.  
    *Responsible Use:* Please verify predictions independently before making decisions based on them.  

    """
)
st.markdown("---")
st.markdown(
    "<p style='text-align: center;'> Thank you for exploring this demo.<br>Have a spam-free day! <br>📬🚀</p>",
    unsafe_allow_html=True
)